:root {
    --form-field-label-font-size: 1em;
    --form-field-data-font-size: 1.01em;
}

.palmyra-form-field-container {
    width: 100%;
    display: flex;
    text-align: left;
    word-break: break-all;
    padding: 5px 5px 0px 5px;
}

.palmyra-form-field-label {
    margin: auto;
    font-size: var(--form-field-label-font-size);
}

.palmyra-form-field-data {
    font-size: var(--form-field-data-font-size);
    width: 100%;
}

/* 
.palmyra-form-field-container .palmyra-form-field-label{
    width: 40%;
}

.palmyra-form-field-container .palmyra-form-field-data{
    width: 60%;
} */

.palmyra-field-group-container {
    width: 100% !important;
    display: flex;
    flex-wrap: wrap;
    /* padding: 10px 10px 10px 20px; */
}

.palmyra-field-group-container-2columns .palmyra-form-field-container {
    width: calc(50%);
    padding: 10px 10px 10px 20px;
}

.palmyra-field-group-container-2columns .palmyra-form-field-container-2colspan {
    width: 100%;
    padding: 10px 10px 10px 20px;
}

.palmyra-field-group-container-2columns .palmyra-form-field-container-2colspan .palmyra-form-field-label {
    width: 20%;
}

.palmyra-field-group-container-2columns .palmyra-form-field-container-2colspan .palmyra-form-field-data {
    width: 80%;
}

.palmyra-field-group-container-3columns .palmyra-form-field-container {
    width: calc(33% - 0px);
    padding: 10px 10px 10px 20px;
}

.palmyra-field-group-container-3columns .palmyra-form-field-container-2colspan {
    width: 67%;
    padding: 10px 20px 10px 20px;
}

.palmyra-field-group-container-3columns .palmyra-form-field-container-2colspan .palmyra-form-field-label {
    width: 19%;
}

.palmyra-field-group-container-3columns .palmyra-form-field-container-2colspan .palmyra-form-field-data {
    width: 81%;
}

.palmyra-field-group-container-3columns .palmyra-form-field-container-3colspan {
    width: 100%;
    padding: 10px 25px 10px 20px;
}

.palmyra-field-group-container-3columns .palmyra-form-field-container-3colspan .palmyra-form-field-label {
    width: 13%;
}

.palmyra-field-group-container-3columns .palmyra-form-field-container-3colspan .palmyra-form-field-data {
    width: 90%;
}

.palmyra-field-group-container-4columns .palmyra-form-field-container {
    width: calc(25% - 5px);
    padding: 10px 10px 10px 20px;
}

.palmyra-field-group-container-4columns .palmyra-form-field-container-2colspan {
    width: 50%;
    padding: 10px 20px 10px 20px;
}

.palmyra-field-group-container-4columns .palmyra-form-field-container-2colspan .palmyra-form-field-label {
    width: 19%;
}

.palmyra-field-group-container-4columns .palmyra-form-field-container-2colspan .palmyra-form-field-data {
    width: 81%;
}

.palmyra-field-group-container-4columns .palmyra-form-field-container-3colspan {
    width: 80%;
    padding: 10px 95px 10px 20px;
}

.palmyra-field-group-container-4columns .palmyra-form-field-container-3colspan .palmyra-form-field-label {
    width: 13%;
}

.palmyra-field-group-container-4columns .palmyra-form-field-container-3colspan .palmyra-form-field-data {
    width: 90%;
}

.palmyra-field-group-container-4columns .palmyra-form-field-container-4colspan {
    width: 100%;
    padding: 10px 30px 10px 20px;
}

.palmyra-field-group-container-4columns .palmyra-form-field-container-4colspan .palmyra-form-field-label {
    width: 10%;
}

.palmyra-field-group-container-4columns .palmyra-form-field-container-4colspan .palmyra-form-field-data {
    width: 95%;
}

.palmyra-form-field-container-2column {
    width: calc(50% - 30px) !important;
}

.palmyra-form-field-container-3column {
    width: calc(33% - 30px) !important;
}

.palmyra-form-field-container-4column {
    width: calc(25% - 30px) !important;
}

.form-error-text {
    margin-left: 0px !important;
}

.MuiFormHelperText-root {
    margin-left: 0 !important;
}