spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mariadb://192.168.1.103:3306
    username: hema
    password: secret
    driverClassName: org.mariadb.jdbc.Driver
