spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mariadb://localhost:3306
    username: root
    password: iamsherlocked@123
    driverClassName: org.mariadb.jdbc.Driver
